grid = mp_grid_create(0, 0, room_width/32, room_height/32, 32, 32)
mp_grid_add_instances(grid,obj_Wall,0)
//mp_grid_add_instances(grid, obj_tuyau_cassable_haut, 0)
//mp_grid_add_instances(grid, obj_tuyau_cassable_bas, 0)
mp_grid_add_instances(grid, obj_tuyau_horiz_01, 0)
mp_grid_add_instances(grid, obj_tuyau_horiz_02, 0)
mp_grid_add_instances(grid, obj_tuyau_verti_02, 0)
mp_grid_add_instances(grid, obj_porte_puzzle, 0)
